name: Update Packagist

on:
  push:
    branches:
      - master

jobs:
  update-packagist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Update Packagist
        env:
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
        run: |
          curl -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username=${{ env.PACKAGIST_USERNAME }}&apiToken=${{ env.PACKAGIST_TOKEN }}' -d'{"repository":{"url":"https://packagist.org/packages/${{ vars.PACKAGIST_PACKAGE_URL_SURFIX }}"}}'
